### ISSUE TITLE
Lightning talk duration?

### ISSUE THREAD

**Issue by parente** [libcce/TriangleJupyter#1]
The schedule lists them at 15 minutes each from 2:15pm  -  3:30pm. Do we want to make them shorter to give more people a chance to talk. I'm thinking that if we're advertising the time slot ahead of time, more people might show up that day with something to say.

Personal opinion: I find talks capped at 5 minutes each highly enjoyable as it encourages people to be more creative and often comedic in their delivery.

Just putting this out there for discussion.

**Comment by libcce** [comment]
I'm fine with 5 min talks. I think I'm more concerned with the time in-between the talks and also allowing for Q&A. Can it be 5-7 min talks with time for one question? So can the slots be for 10 min?

**Comment by parente** [comment]
Makes sense. Telling people five to make sure they stop and leave a few for q&a plus switchover works. However you’d like to do it.

**Comment by libcce** [comment]
I've made the change :)
