### ISSUE TITLE
Proposed lightning talk structure

### ISSUE THREAD

**Issue by libcce** [libcce/TriangleJupyter#10]
* Timekeeper w/ laptop that makes alarm sound when speaker time is finished, operated by helper(s), use of time cards
* Etherpad (https://pad.carpentries.org/TriangleJupyterDay) or Google Doc (to require auth) to collect notes (timekeeper, follow-up blog post based on notes, people who don't want to sign up for Gitter) and take questions along with Gitter channel (https://gitter.im/TriangleJupyter/Lobby, people posting links to share, etc)
* Leave questions until the end of the lightning talk block
* Allow presenters to use their own laptops (have them check the projector connection when they arrive)
  * Have presenters test connections and remind them to do so throughout the day.
  * Have an on-deck area for the person who is next and fall back on that person presenting if the current presenter has a laptop, preso, etc. issue that A/V cannot resolve quickly. Move that presenter to the end of the block.
* Collect links to their presentations/material via GitHub PRs (link directly from talk title on the Information page)
  * Remind everyone about this in gitter/etherpad and offer assistance if people don't want to do it themselves
  * Remind everyone that they can send a PR!

Proposed MCs for sessions:

8:45 - 10:45 - Chris E.  (confirmed)
11:00 - 14:00 - Tony F. (confirmed)
14:15 - 15:15 - Devin S. (confirmed)
15:30 - 17:00 - Chris C.  (confirmed)
17:00 - 17:10 - Ginny G. (confirmed)

**Comment by libcce** [comment]
Note: Tal/Diveplane has asked for an announcement that they will be doing a demo at lunchtime @tonyfast and @parente @tonyfast will stay later to help with Jupyter installation/additional help, we will need to announce at the end @gghezzo. We need to confirm with JJ what time we will have the space for.

**Comment by parente** [comment]
I'll write this all up in an MC guide and update the spreadsheet.

**Comment by parente** [comment]
Started summarizing day-of organizer / MC logistics at https://libcce.github.io/TriangleJupyter/logistics/organizers.html (source: https://github.com/libcce/TriangleJupyter/blob/master/logistics/organizers.md) linked from the bottom of the Information page on the site.

@libcce (and anyone else) feel free to add / edit
