### ISSUE TITLE
Inquiry into Carolina Club about bathrooms

### ISSUE THREAD

**Issue by libcce** [libcce/TriangleJupyter#11]
Getting the exact count from JJ per @gghezzo

**Comment by libcce** [comment]
@gghezzo here are the details:

Downstairs
Women’s – 8 toilets
Men’s – 4 toilets and 4 urinals

Upstairs
Women’s – 8 toilets
Men’s – 4 toilets and 4 urinals

**Comment by parente** [comment]
I think we can close this issue as we have the info requested. Feel free to reopen if not.
