### ISSUE TITLE
Organizer sync on the 5th

### ISSUE THREAD

**Issue by parente** [libcce/TriangleJupyter#13]
Calendar invite sent via email. Forward to anyone who should be there. We should go through all of the issues here in the issue tracker and make sure we've got everything covered plus someone assigned to take care of it.

**Comment by parente** [comment]
@libcce Can you please test the Zoom link I included in the invite to make sure it doesn't prompt you to log in to Valassis SSO. I believe I've set it up to allow everyone access, even if they don't have the Zoom client.

**Comment by libcce** [comment]
@parente I didn't have to log in. Looks good!
