### ISSUE TITLE
Parking

### ISSUE THREAD

**Issue by parente** [libcce/TriangleJupyter#15]
Should we put in a special request to UNC operations to notify them that we're going to have 120 visitors all trying to park in the Ram's Head deck?

The form here says we should notify them at least a week in advance. https://move.unc.edu/events/request-forms/event-request/

**Comment by thtriumph** [comment]
@parente - good idea - do you want me to submit it?

**Comment by parente** [comment]
@thtriumph That would be great. Thank you!

**Comment by parente** [comment]
Just to clarify: We're not looking to pay for parking for everyone, just to make sure there's going to be space available.

**Comment by thtriumph** [comment]
@parente Request submitted
