### ISSUE TITLE
Get name tag stickers

### ISSUE THREAD

**Issue by parente** [libcce/TriangleJupyter#18]
@thtriumph: do you have stickers and markers that we can set out at the registration desk for attendees and staff to write their names on?

**Comment by gghezzo** [comment]
We will also need dark sharpie markers. It would be nice to have a pack of 8 to 10 Sharpies.

**Comment by thtriumph** [comment]
Yes, I will bring name tag stickers and markers.

**Comment by parente** [comment]
If we can get a few different colors, that will also help us distinguish staff, presenter, and attendee.

**Comment by thtriumph** [comment]
Will do

**Comment by parente** [comment]
@thtriumph mentioned on our call this morning that she is bringing stickers, markers, and colored dots to identify helpers, speakers, etc. I think we're good to go!
