### ISSUE TITLE
Exit survey

### ISSUE THREAD

**Issue by parente** [libcce/TriangleJupyter#19]
Look at what was used for JupyterDay ATL. Post a link to a new version for this event on the JDitT website by the end of the event. Use a google form or surveymonkey or ...

~Or do what you like / think can be improved at the end of the event in the Etherpad / Google Doc (one up, one down). Can do that along the way to gather realtime feedback.~

**Comment by tonyfast** [comment]
https://www.surveymonkey.com/results/SM-JHDZFB7KL/

**Comment by parente** [comment]
@libcce posted this to the information page for attendees. I think we're good.
