### ISSUE TITLE
Registration setup, layout

### ISSUE THREAD

**Issue by parente** [libcce/TriangleJupyter#20]
* Clipboards for people helping with registration to free up space on the sponsor swag table
* Printout of the Eventbrite list

**Comment by parente** [comment]
cc @gghezzo

**Comment by parente** [comment]
@libcce Can you add Ginny as a collab on this project so we can assign?

**Comment by libcce** [comment]
@parente @gghezzo I sent her an invite a while back but I just saw that she hasn't accepted it.
