### ISSUE TITLE
Sponsor material/swag

### ISSUE THREAD

**Issue by libcce** [libcce/TriangleJupyter#6]
Sponsor material and swag to be displayed at the registration desk on the day of the event. Reach out to the following sponsors to confirm:

- [ ] Odum (Waiting to hear back)
- [x] Diveplane (Tal to bring materials, table for demo)
- [x] Code Ocean (Seth will bring bags, shirts, pens and stickers)
- [x] Project Jupyter (Pete will bring stickers) 
- [x] AAP (Devin bringing flyers, mints for tables)
- [x] NumFOCUS (Pete and Chris C will bring stickers)
- [x] UNC Chapel Hill Libraries (Therese bringing flyers)
- [x] Valassis Digital (Pete / Gene bringing materials)

**Comment by libcce** [comment]
@parente sponsors will have to arrive early for us to display their swag/material. Will you be following up with them with a time of arrival?

**Comment by parente** [comment]
Yep. I figured we'll email speakers with logistics (projector connections, when to test, adapters to bring, what we'll have, what to do as a backup, etc.) and sponsors with logistics (when to show up, where to setup, etc.) after our sync on Monday when we're all agreed on those details.

**Comment by parente** [comment]
I'll email Odum again today.

**Comment by parente** [comment]
I'll also email sponsors to arrive by 7:45 to set things out.

**Comment by parente** [comment]
Emailed with final space info and request to arrive by 7:45 AM
