### ISSUE TITLE
Order JupyterDay in the Triangle Balloons

### ISSUE THREAD

**Issue by libcce** [libcce/TriangleJupyter#7]
JupyterDay in the Triangle balloons will be used to help with directions.
https://www.partycity.com/balloons-custom

Alternatively, sandwich boards can be used via the Libraries.

**Comment by libcce** [comment]
25 Balloons ordered. Delivery date is November 6. If it doesn't arrive by 7, reach out to @thtriumph about signs via the Libraries.

**Comment by libcce** [comment]
Balloons look good. Text is a little small but the logo and text came out fine. I will be going to Harris Teeter or other this Saturday to see if I can have the balloons blown up on Monday. Otherwise, will have to be this weekend. This means that I will be showing up like a clown with 25 balloons. I'm going to ask JJ if I can having parking nearby since I will have balloons and a big sign in tow. @thtriumph @parente

**Comment by parente** [comment]
# 🤡

**Comment by thtriumph** [comment]
Chris - maybe pick up a small bottle of gas at one of the craft stores so we can blow them up at the CC (?)

Therese Triumph
Interim Head of Kenan Science Library, UNC-CH

On Nov 8, 2018, at 10:08 AM, Peter Parente <notifications@github.com<mailto:notifications@github.com>> wrote:

🤡

**Comment by libcce** [comment]
Maybe I am a little loop this morning but the first image that popped into my mind was us blowing up the balloons at the closing ceremony, ha!

JJ tells me that I can pull into the circle outside the building to offload the sign and the balloons. I'm going to blow them up at a place beforehand so they can tie strings around the balloons for us. It's going to be great! Welcome to the Jupyter circus :)

**Comment by cbcunc** [comment]
Be sure to drive your clown car.

**Comment by libcce** [comment]
Balloons ready
