### ISSUE TITLE
A/V @ Carolina Club

### ISSUE THREAD

**Issue by libcce** [libcce/TriangleJupyter#8]
An A/V tech support will be on hand for the event.

@libcce checking w/ JJ re: projector specifications...

Carolina Club has some dongles/adaptors, but not all.
@parente @cbcunc do you have adaptors/dongles to bring?

* ~[x] HDMI -> HDMI input~
* [x] Lightning -> HDMI
* [x] USB-C -> HDMI
* [x] MiniDisplay Port -> HDMI
* [x] DVI -> HDMI

**Comment by parente** [comment]
@libcce Any word from JJ about the projector input(s)?

**Comment by libcce** [comment]
From JJ: 

We have a mac dongle and pc laptop dongle.  I would suggest having anyone with a mac or newer laptop bring their own just in case it is a different version.  For 99% of our events we are good with what we have but every now and then, especially the newer MACs we see different dongles.

**Comment by libcce** [comment]
If Valassis Digital/ you @parente and UNC Libraries/ @thtriumph want to bring some additional adaptors just in case, that might cover us. We will definitely need to ask the speakers to bring their own and to hopefully arrive early at 8-8:30 to test.

**Comment by parente** [comment]
I've put in a request to our IT to borrow what adapters we have on hand for the day to serve as backup for presenters and the venue A/V support staff.

**Comment by parente** [comment]
IT responded quickly and had all 4 adapters in the description in stock. I'll be bringing them.
