### ISSUE TITLE
Find 5-10 helpers and assign tasks during event

### ISSUE THREAD

**Issue by libcce** [libcce/TriangleJupyter#9]
Initial breakdown of helpers:

* 1-2 UNC Libraries helpers at the registration desk with @gghezzo
* 1-2 helpers for A/V, loading presentations, presentation timekeeping, notetaking w/ MCs
* 1-2 helpers for Q&A sessions (microphones)
* 1-2 helpers floating to help with miscellaneous
* 1-2 helpers for directions, balloons, other materials

**Comment by parente** [comment]
I can point folks at Valassis Digital at this ticket Monday to see if anyone wants to sign up to help.

**Comment by libcce** [comment]
A/V tech support will be available via the Carolina Club, see https://github.com/libcce/TriangleJupyter/issues/8. 

I think at least two of us need to arrive earlier than 7:50 am (I will probably be one of them), to set up signs, the poster, set up the name tags, registration list. There is another issue about getting balloons for the event, for signage https://github.com/libcce/TriangleJupyter/issues/7. I can arrive at 7 am that day. Will need to check with JJ on when we can get into the Club.

We won't be pre-loading slides on a laptop for the speakers. They will use their own devices. There is an issue about dongles here https://github.com/libcce/TriangleJupyter/issues/8. One of the helpers will help with loading slides before/during the event. We can ask them to point to their slides/notebook ahead of time (which I think we should do).

**Comment by GeneFerruzza** [comment]
I'd be happy to help at the registration desk with Ginny

**Comment by thtriumph** [comment]
Chris - I can be there early (7 am?) to help you put out signs

**Comment by benwood33** [comment]
I can help with misc or being a mic runner.

**Comment by simpsonjw** [comment]
I can help with Q&A sessions/ microphones

**Comment by nshah15** [comment]
I can also help with the Q&A session
- Nidhi Shah

**Comment by thtriumph** [comment]
Here is a spreadsheet with the helper tasks and the people who signed up for them. we need to add times to the tasks.
https://docs.google.com/spreadsheets/d/1C3n8QI5DQ7z_kIhnsbRa7yy9quUQ5A6pXMeGiW2Umg4/edit?usp=sharing

**Comment by simpsonjw** [comment]
@thtriumph Can you add Hannah Mingus to help with directions, balloons, other materials? I'm only able to view the spreadsheet. Thanks!

**Comment by thtriumph** [comment]
Done :)

**Comment by parente** [comment]
@thtriumph I can be at the CC by 7 AM as well to help.

**Comment by libcce** [comment]
@thtriumph thanks for putting together the spreadsheet. I think that covers what we need help with. Nice catch with regard to clean up. There will be some, like the balloons, materials, etc. The rest will be picked up by CC. I've added my name to clean up.

**Comment by simpsonjw** [comment]
@thtriumph we have a new team member who is interested in coming as well. Any chance you guys need another volunteer? Thanks!

**Comment by grissomajd** [comment]
@thtriumph I just spoke to @simpsonjw and would love to volunteer when you need helpers in the morning. Thanks!

**Comment by thtriumph** [comment]
@grissomajd Please add your name to the Google spreadsheet (the times are estimates).
https://docs.google.com/spreadsheets/d/1C3n8QI5DQ7z_kIhnsbRa7yy9quUQ5A6pXMeGiW2Umg4/edit?usp=sharing

**Comment by thtriumph** [comment]
weird - I have made the google spreadsheet public but it doesn't seem to allow people in ??

**Comment by grissomajd** [comment]
I had to request permission, but I was able to get in and edit it now.

**Comment by parente** [comment]
Ginny, Pete will also be there til 5:30 (or whenever we leave the space) to help clean up.

**Comment by GeneFerruzza** [comment]
Gene will be there too.

**Comment by thtriumph** [comment]
@parente Brian Q will be there all day except between from 10:30 am to 12:30 pm

**Comment by thtriumph** [comment]
Should I breakout the Task spreadsheet with times according to the speaker sessions so we can map out the helpers?

**Comment by thtriumph** [comment]
@parente @libcce I have updated the Tasks & Helper spreadsheet - Please take a look at it and assign yourself to some of the tasks. I broke the task down so that everyone can take a turn a different tasks. I do think we need all three helpers at the registration table for the morning sign-in.

**Comment by parente** [comment]
@thtriumph Looks like we're ships passing in the night. I just sent you an invite to our private Sheet with the accepted talk reviews and a detailed schedule broken down at 5 minute intervals. It should bei in your @email.unc.edu account.

**Comment by thtriumph** [comment]
@parente yup got it!

**Comment by parente** [comment]
It's OK to add the details to the public one, especially since we can't share the one I sent you with everyone. Just wanted you to have all the information.

**Comment by thtriumph** [comment]
Got it! Thanks

**Comment by thtriumph** [comment]
@parente Just talked to the UNC parking people about the "parking registration" form I sent in. I was told we do not need the form because we are not paying for the attendees' parking. The next closest public parking is at the corner of Raleigh Rd & Country Club Rd (10-15 min walk to CC). So, let's make sure we reiterate to the attendees that carpooling and public transportation is best.

**Comment by thtriumph** [comment]
@parente YES Rams Deck it #1

**Comment by simpsonjw** [comment]
Hi @thtriumph, what time do we need to arrive?

**Comment by thtriumph** [comment]
@parente @libcce what time should the helpers arrive? Several of us are arriving at 7

**Comment by libcce** [comment]
@thtriumph @parente Honestly, anyone that can arrive at 7am will be great. It will be a less hectic time and will allow us to be better prepared but I know that everyone is a volunteer, so whatever time is best for them. Arriving early definitely helps us though.

**Comment by parente** [comment]
FWIW, I broke the detailed schedule out of the Google Sheet without all the reviewer comments into https://docs.google.com/spreadsheets/d/1ZSF4S8PDmfbya5AN0OXLegoauoV3XyLuKEJZB6QSpqI/edit?usp=sharing so everyone here can see it. I'll add this link to the [organizer notes](https://libcce.github.io/TriangleJupyter/logistics/organizers.html) page on the site as well in a minute.

I'll print some number of copies of the spreadsheet for organizers + volunteers to have on hand during the event.

**Comment by thtriumph** [comment]
@simpsonjw and all helper, feel free to around 7 am if possible.

**Comment by parente** [comment]
We setup an invite-only Gitter channel (https://gitter.im/TriangleJupyter/Helpers) for more real-time communication with the helpers today and tomorrow.

I think we're good to close this out.
